- hosts: node
  remote_user: azureuser
  become: yes
  tasks:
    - name: create new deployment
      command: kubectl apply -f /home/azureuser/Deployment.yaml
    - name: create new service
      command: kubectl apply -f /home/azureuser/Service.yaml
